### ISSUE TITLE
Create PHP Router

### ISSUE THREAD

**Issue by davy-beauzil** [davy-beauzil/p5-blog-php#3]
estimated time : 1 day

Create the router who allows to : 
- [x] redirect to the good method and controller
- [x] extract parameters ($_GET, $_POST, ...)
- [x] redirect to 404 page if page is not found

**Comment by TechnoCraftDevops** [comment]
@davy-beauzil

**Comment by davy-beauzil** [comment]
@TechnoCraftDevops 
https://github.com/davy-beauzil/p5-blog-php/pull/13/commits/13b37460313320831f44fe51f0b46c320b72f6d3
